<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Must remain on .NET 7 (generic math baseline) -->
    <TargetFramework>net7.0</TargetFramework>
    <NoWarn>CA1725,CA1716,CS1591,CA1715</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Package metadata -->
  <PropertyGroup>
    <Product>SMath</Product>
    <Title>SMath</Title>
    <Version>1.2.0</Version>
    <Description>Alternative math library based on .NET 7 generic math.</Description>
    <PackageTags>math; generic-math; geometry; combinatorics; statistics; vectors; csharp</PackageTags>
    <PackageProjectUrl>https://github.com/jirikostiha/smath</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)..\..\ijkdata.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\readme.md" Link="readme.md" Pack="true" PackagePath="readme.md" />
    <None Update="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
