<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup>
        <!-- Testing -->
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageVersion Include="xunit.v3" Version="4.0.1" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
        <PackageVersion Include="NSubstitute" Version="6.2.0" />
        <!-- Benchmarking -->
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

</Project>
