<Project>

	<!-- Common properties shared across all projects -->
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Deterministic>true</Deterministic>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<!-- Shared package / repository metadata -->
	<PropertyGroup>
		<Authors>Jiri Kostiha</Authors>
		<Company />
		<Copyright>Copyright © 2022 Jiri Kostiha</Copyright>
		<RepositoryUrl>https://github.com/jirikostiha/smath</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<!-- Output paths -->
	<PropertyGroup>
		<BaseOutputPath>..\..\..\artf\$(MSBuildProjectName)\bin\</BaseOutputPath>
		<BaseIntermediateOutputPath>..\..\..\artf\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
	</PropertyGroup>

</Project>
