name: Code Analysis

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**.cs'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**.cs'
  schedule:
    - cron: '40 14 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v4
