name: Commit Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .github/commitlint_config.js

      - name: Check no !fixup commits
        if: ${{ github.event_name == 'pull_request' }}
        uses: 13rac1/block-fixup-merge-action@v2.0.0

      - name: Delete workflow logs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ${{ github.workflow }}
          retain_days: 3
          keep_minimum_runs: 3
