name: Publish

env:
  sln-path: "./src/smath.slnx"
  package-dir: "packages"

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.tag }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "8.0.x"

      - name: Publish
        run: dotnet publish "${{ env.sln-path }}" -c Release -p:ContinuousIntegrationBuild=true

      - name: Pack
        run: dotnet pack "${{ env.sln-path }}" -c Release -o "${{ env.package-dir }}" --no-build -p:ContinuousIntegrationBuild=true

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: jiri

      - name: Publish to Nuget.org
        run: dotnet nuget push "${{ env.package-dir }}"/**/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
