name: Release

env:
  sln-path: "./src/smath.sln"
  build-dir: "build"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .Net ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: .Net info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore "${{ env.sln-path }}"

      - name: Test
        run: dotnet test "${{ env.sln-path }}" --no-restore -c Release

      - name: Build release
        run: dotnet build "${{ env.sln-path }}" --no-restore -c Release -o "${{ env.build-dir }}"

      - name: Upload artifact - binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: "${{ env.build-dir }}"
          retention-days: 90

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: "${{ env.build-dir }}"

      - name: Zip binaries
        uses: vimtor/action-zip@v1
        with:
          files: "${{ env.build-dir }}"
          dest: binaries.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          prerelease: true
          draft: false
          generate_release_notes: true
          files: binaries.zip
          token: ${{ secrets.GITHUB_PACKAGE_PUSH_PAT }}

      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 8
          delete_tags: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
